### ISSUE TITLE
is_async problem

### ISSUE THREAD

**Issue by Digdgeo** [ale-cristofori/geotweet#2]
Hi, I am try to run this in Ubuntu (18.04) and get this error:

```
TypeError: filter() got an unexpected keyword argument 'is_async' 
Traceback (most recent call last):
  File "/home/diego/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qweetgis/search/main.py", line 795, in on_get_stream
    self.get_geo_search()
  File "/home/diego/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qweetgis/search/main.py", line 836, in get_geo_search
    self.activate_stream(accuracy, src_bbox=src_bbox)
  File "/home/diego/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qweetgis/search/main.py", line 749, in activate_stream
    result = myStream.filter(locations=src_bbox, is_async=True)
TypeError: filter() got an unexpected keyword argument 'is_async'

```

The is_async parameter is just in 2 lines. If I remove the parameter in that lines I don't get the error but nothing happens, just the tool running but without give any results.

Thanks

**Comment by ale-cristofori** [comment]
Hi,
The error is coming from tweepy. 
See this 

https://github.com/uclatommy/tweetfeels/issues/50

By the looks of it, maybe when you installed tweepy it did not do it correctly and you are maybe missing a dependency.

Try to install tweepy again and let me know, if it is still an issue. I have just tested it in Windows and it still works ok.
